version: '3.7'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./envs/prod/env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/prod/env.prod.db
  nginx:
    build: ./envs/prod/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/envs/prod/mediafiles
      o: bind
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: $PWD/envs/prod/staticfiles
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/envs/prod/postgres_db_data
      o: bind
